name: Quran Stream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Stream Al-Luhaidan
        env:
          RTMP_URL: ${{ secrets.RTMP_URL }}
        run: |
          ffmpeg -re \
          -i "https://stream.zeno.fm/radio/online-quran-radio-quran-in-arabic-by-sheikh-mohammed-al-luhaidan" \
          -vn \
          -c:a aac \
          -b:a 128k \
          -f flv "$RTMP_URL"
